// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreatePostInput struct {
	AuthorID string `json:"authorId"`
	Content  string `json:"content"`
}

type CreateUserInput struct {
	Name *string `json:"name,omitempty"`
}

type Mutation struct {
}

type Post struct {
	ID      string `json:"id"`
	Author  *User  `json:"author"`
	Content string `json:"content"`
}

type Query struct {
}

type Subscription struct {
}

type User struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Following []*User `json:"following,omitempty"`
	Followers []*User `json:"followers,omitempty"`
}
